### ISSUE TITLE
showing ValueError: math domain error

### ISSUE THREAD

**Issue by vinayakumarr** [pandas-ml/pandas-ml#98]
How to correct this?
![untitled](https://cloud.githubusercontent.com/assets/18217467/21587020/68b0b944-d0fd-11e6-8ea9-bff0442fd50e.png)

**Comment by scls19fr** [comment]
Hello,

Minimal code sample that raises this exception could help.

Kind regards

**Comment by vinayakumarr** [comment]
Could you please tell how to correct this or do you have any stable library for calculating the statistical measures including true positive rate and false positive rate?

**Comment by scls19fr** [comment]
I suggest reading first what is a SSCCE (Short, Self Contained, Correct (Compilable), Example) or a MWE (Minimal Working Example).

Avoid posting image. Post exception / traceback as text (with triple backquote) so it will be much easier to search for a fix. Moreover it will be easier for other people who encountered such bug to find a way to fix it.

**Comment by vinayakumarr** [comment]
Actual
0          43084    1639   1576  13875   419    60593
1          13144  201420  21303   1729     0   237596
2            132      15   4013      6     0     4166
3              1       7      1     56     5       70
4           6005      23    552    717  1307     8604
__all__    62366  203104  27445  16383  1731   311029
(311029,)
(311029,)
/usr/local/lib/python2.7/dist-packages/pandas_ml/confusion_matrix/stats.py:60: RuntimeWarning: overflow encountered in long_scalars
  num = df[df > 1].dropna(axis=[0, 1], thresh=1).applymap(lambda n: choose(n, 2)).sum().sum() - np.float64(nis2 * njs2) / n2
/usr/local/lib/python2.7/dist-packages/pandas_ml/confusion_matrix/stats.py:61: RuntimeWarning: overflow encountered in long_scalars
  den = (np.float64(nis2 + njs2) / 2 - np.float64(nis2 * njs2) / n2)
/usr/local/lib/python2.7/dist-packages/pandas_ml/confusion_matrix/bcm.py:304: RuntimeWarning: overflow encountered in long_scalars
  (self.TN + self.FP) * (self.TN + self.FN)))
Traceback (most recent call last):
  File "all.py", line 68, in <module>
    cm.stats()
  File "/usr/local/lib/python2.7/dist-packages/pandas_ml/confusion_matrix/abstract.py", line 393, in stats
    d_stats['class'] = self.stats_class
  File "/usr/local/lib/python2.7/dist-packages/pandas_ml/confusion_matrix/abstract.py", line 347, in stats_class
    binary_cm_stats = binary_cm.stats()
  File "/usr/local/lib/python2.7/dist-packages/pandas_ml/confusion_matrix/bcm.py", line 358, in stats
    d = map(lambda stat: (stat, getattr(self, stat)), lst_stats)
  File "/usr/local/lib/python2.7/dist-packages/pandas_ml/confusion_matrix/bcm.py", line 358, in <lambda>
    d = map(lambda stat: (stat, getattr(self, stat)), lst_stats)
  File "/usr/local/lib/python2.7/dist-packages/pandas_ml/confusion_matrix/bcm.py", line 304, in MCC
    (self.TN + self.FP) * (self.TN + self.FN)))
ValueError: math domain error

**Comment by sinhrks** [comment]
@scls19fr I've recieved sample file from @vinayakumarr. Based on the error, the issue is caused by arithmetic overflow in ``class_agreement``. 

I don't know the detail of the algorithm of ``class_agreement``, but can the formula be changed to use smaller intermediate values?

#### Reproduction procedure

```
import pandas as pd
import pandas_ml as pdml
predicted = p

predicted = pd.read_csv('predicted.txt')
expected = pd.read_csv('expected.txt')

cm = pdml.ConfusionMatrix(expected.iloc[:, 0], predicted.iloc[:, 0])
cm.stats()
```

[predicted.txt](https://github.com/pandas-ml/pandas-ml/files/686875/predicted.txt)
[expected.txt](https://github.com/pandas-ml/pandas-ml/files/686878/expected.txt)

**Comment by scls19fr** [comment]
An other idea is to compare results with R [caret](http://caret.r-forge.r-project.org/) package
but I'm quite busy these days.
